### ISSUE TITLE
软件升级到1.7版本后无法激活

### ISSUE THREAD

**Issue by hui3215** [hazukieq/Yporaject#4]
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！
# 软件升级到1.7版本后无法激活！！！

**Comment by hazukieq** [comment]
您好！我很高兴收到您的反馈，但您提供的信息过于简略，烦请您按以下模板反馈问题，否则无助于他人了解和解答您的问题，谢谢！

---
### 提问模板
#### 描述你在学习中遇到的问题

**为避免无效问题和冗余问题，提问前请确认: **

1. 你确定 Google 不能解决你的问题
2. 你确定已有的 issue 不能解决你的问题
3. 你确定 issue 的 title 按照格式如下：[问题]：问题描述



**Describe the Problem 描述你遇到的问题**

 A clear and concise description of what the problem is. 简洁有效的说明。



**To Reproduce 如何重现问题**

Steps to reproduce the behavior 简要描述问题的发生



**Expected behavior 期待解决的效果**

 A clear and concise description of what you expected to happen. 简单描述。



**Screenshots 截图** 

If applicable, add screenshots to help explain your problem.
如有必要，可以截图说明 



**Environmemt 环境版本说明 **

- OS: [e.g. win] 说明操作系统
- Rust Version 说明语言及版本号
- Typora Package Version 软件版本 



**Additional Text 其他补充**

Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by hazukieq** [comment]
您好，经我自己亲自验证，Typora 最新版 1.7.4 仍旧是可以激活成功的，请您确认自己操作是否有误，或是否正确按照教程步骤执行！

**该 issue 经核实确认: 新版本仍可激活，现将其关闭**
> 提问不规范，无效提问
